# Generated by Django 5.1.7 on 2025-05-01 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_signalpole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalpole',
            name='direction',
        ),
    ]
