# Generated by Django 5.1.7 on 2025-05-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_signalpole_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalpole',
            name='direction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
