# Generated by Django 5.1.7 on 2025-03-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_user_selected_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.IntegerField(choices=[(10, '10대'), (20, '20대'), (30, '30대'), (40, '40대'), (50, '50대'), (60, '60대 이상')])),
                ('gender', models.IntegerField(choices=[(1, '남성'), (2, '여성')])),
                ('slow', models.FloatField()),
                ('normal', models.FloatField()),
                ('fast', models.FloatField()),
            ],
            options={
                'unique_together': {('age_group', 'gender')},
            },
        ),
    ]
