# Generated by Django 5.1.7 on 2025-03-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_speedrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedrecommendation',
            name='age_group',
            field=models.IntegerField(choices=[(0, '10대 이하'), (10, '10대'), (20, '20대'), (30, '30대'), (40, '40대'), (50, '50대'), (60, '60대 이상')]),
        ),
    ]
