# Generated by Django 5.1.7 on 2025-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_speedrecommendation_age_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='selected_speed',
            new_name='max_speed',
        ),
        migrations.AddField(
            model_name='user',
            name='min_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
